#!/usr/bin/osascript -l JavaScript

function run(argv) {
  const browser = Application(argv[0])
  const urls = argv.slice(1)

  // With no arguments, open empty window
  if (urls.length === 0) {
    browser.Document().make()
    browser.activate()
    return
  }

  // Open in reverse order so they show in given order
  urls.reverse().forEach(url => {
    browser.Document({url: url}).make()
    browser.activate()
  })
}
