#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function run(argv) {
  const browser = Application(argv[0])
  const outFormat = argv[1]

  const currentTab = browser.windows[0].currentTab

  switch (outFormat) {
    case "url": return alfredArgs(currentTab.url())
    case "title": return alfredArgs(currentTab.name())
    case "url_title": return alfredArgs(currentTab.url() + "|" + currentTab.name())
    default: throw "Unrecognised type: " + outFormat
  }
}
