#!/usr/bin/osascript -l JavaScript

function run(argv) {
  const browser = Application(argv[0])
  const windowMode = argv[1] === "1" ? "incognito" : "normal"
  const urls = argv.slice(2)

  // With no arguments, open empty window
  if (urls.length === 0) {
    browser.Window({ mode: windowMode }).make()
    browser.activate()
    return
  }

  // Open in reverse order so they show in given order
  urls.slice().reverse().forEach(url => {
    browser.Window({ mode: windowMode }).make()
    browser.windows[0].activeTab.url = url
    browser.activate()
  })
}
