#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function run(argv) {
  const browser = Application(argv[0])
  const activeTab = browser.windows[0].activeTab
  const tabURL = activeTab.url()

  activeTab.close()
  return alfredArgs(tabURL)
}
