#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function run(argv) {
  const browser = Application(argv[0])
  const windows = argv[1] === "1" ? browser.windows() : [browser.windows()[0]]
  const outFormat = argv[2]
  const matchString = argv[3]

  const matchingTabs = windows
    .flatMap(window => window.tabs())
    .filter(tab => tab !== null)
    .map(tab => [tab.url(), tab.name()])
    .filter(tab => !tab[0].includes(matchString))

  switch (outFormat) {
    case "url": return alfredArgs(matchingTabs.map(tab => tab[0]))
    case "title": return alfredArgs(matchingTabs.map(tab => tab[1]))
    case "url_tab_title": return alfredArgs(matchingTabs.map(tab => tab[0] + "\t" + tab[1]))
    case "title_tab_url": return alfredArgs(matchingTabs.map(tab => tab[1] + "\t" + tab[0]))
    case "url_title": return alfredArgs(matchingTabs.map(tab => tab[0] + "|" + tab[1]))
    default: throw "Unrecognised type: " + outFormat
  }
}
