#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function lookFor(matchString, inText, useRegex) {
  if (useRegex) return RegExp(matchString).test(inText)
  return inText.includes(matchString)
}

function run(argv) {
  const browser = Application(argv[0])
  const windows = argv[1] === "1" ? browser.windows() : [browser.windows()[0]]
  const matchString = argv[2]
  const regex = argv[3] === "1"

  const matchingTabs = windows
    .flatMap(window => window.tabs())
    .filter(tab => tab !== null)
    .filter(tab => lookFor(matchString, tab.url(), regex))

  const tabURLs = matchingTabs.map(tab => tab.url())

  // Close in reverse order
  matchingTabs.reverse().forEach(tab => tab.close())
  return alfredArgs(tabURLs)
}
