#!/usr/bin/osascript -l JavaScript

function run(argv) {
  const browser = Application(argv[0])
  const javascriptCode = argv[1]

  return browser.windows[0].activeTab.execute({ javascript: javascriptCode })
}
