#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function frontmostBrowserName() {
  const getBrowser = $("~/Library/Application Support/Alfred/Automation/Tasks/com.alfredapp.automation.core/safari/.common/get-frontmost-browser").stringByExpandingTildeInPath.js

  const task = $.NSTask.alloc.init
  const stdout = $.NSPipe.pipe

  task.executableURL = $.NSURL.alloc.initFileURLWithPath("/usr/bin/env")
  task.arguments = [getBrowser]
  task.standardOutput = stdout
  task.launchAndReturnError(false)

  const dataOut = stdout.fileHandleForReading.readDataToEndOfFile
  const stringOut = $.NSString.alloc.initWithDataEncoding(dataOut, $.NSUTF8StringEncoding).js

  if (task.terminationStatus !== 0) throw "Did not find a supported web browser"
  return stringOut.trim()
}

function browserVariant(appName) {
  const webkitVariants = ["Safari", "Webkit", "Orion"]
  const chromiumVariants = ["Google Chrome", "Chromium", "Opera", "Vivaldi", "Brave Browser", "Microsoft Edge", "Arc"]

  if (webkitVariants.some(browserName => appName.startsWith(browserName))) return { app: Application(appName), variant: "webkit" }
  if (chromiumVariants.some(browserName => appName.startsWith(browserName))) return { app: Application(appName), variant: "chromium" }
  throw `${appName} is not a supported browser: ${webkitVariants.concat(chromiumVariants).join(", ")}`
}

function run(argv) {
  const targetBrowser = argv[0]
  const allowEmptyWindows = argv[1] === "1"

  // Find browser
  let browser

  try {
    browser = targetBrowser === "frontmost_browser" ?
      browserVariant(frontmostBrowserName()) :
      browserVariant(targetBrowser)
  } catch(error) {
    if (allowEmptyWindows) return
    throw error
  }

  // Check if running
  if (!browser.app.running()) {
    if (allowEmptyWindows) return
    throw `${browser.app.name()} is not running.`
  }

  // Grab windows
  const allWindows = browser.app.windows

  if (allWindows.length === 0) {
    if (allowEmptyWindows) return
    throw "No windows found."
  }

  // Act on tabs
  const currentTab = browser.variant === "webkit" ? allWindows[0].currentTab : allWindows[0].activeTab
  const tabURL = currentTab.url()

  currentTab.close()
  return alfredArgs(tabURL)
}

