#!/usr/bin/osascript -l JavaScript

const fileManager = $.NSFileManager.defaultManager
const finder = Application("Finder")

function envVar(varName) {
  return $.NSProcessInfo
    .processInfo
    .environment
    .objectForKey(varName).js
}

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function isDir(path) {
  const ref = Ref()
  fileManager.fileExistsAtPathIsDirectory(path, ref)
  return ref[0]
}

function pathToFinderItem(path) {
  // Writability check
  if (!fileManager.isWritableFileAtPath(path)) throw "Cannot write to path: " + path

  // Split path components
  const dirComponents = $(path).stringByDeletingLastPathComponent.js.split("/").slice(1)
  const baseComponent = $(path).lastPathComponent.js

  // Details change if on startup disk or external volume
  const [disk, breadcrumbs] = dirComponents[0] === 'Volumes' ?
    [finder.disks.byName(dirComponents[1]), dirComponents.slice(2)] :
    [finder.startupDisk(), dirComponents]

  // Join as Finder item
  const finderDirpath = breadcrumbs.reduce(
    (container, dir) => container.folders.byName(dir),
    disk
  )

  return isDir(path) ?
    finderDirpath.folders.byName(baseComponent) :
    finderDirpath.files.byName(baseComponent)
}

function run(argv) {
  const mode = argv[0]
  const finderComment = argv[1]
  const allPaths = argv.slice(2).map(path => pathToFinderItem(path))

  switch (mode) {
    case "read": return alfredArgs(allPaths.map(p => p.comment()))
    case "set": return allPaths.forEach(p => p.comment = finderComment)
    case "clear": return allPaths.forEach(p => p.comment = "")
    default: throw "Unrecognised mode: " + mode
  }
}
