#!/usr/bin/osascript -l JavaScript

function alfredArgs(args) {
  return JSON.stringify({ alfredworkflow: { arg: args } })
}

function run(argv) {
  const browser = Application(argv[0])
  const outFormat = argv[1]

  const activeTab = browser.windows[0].activeTab

  switch (outFormat) {
    case "url": return alfredArgs(activeTab.url())
    case "title": return alfredArgs(activeTab.name())
    case "url_tab_title": return alfredArgs(activeTab.url() + "\t" + activeTab.name())
    case "title_tab_url": return alfredArgs(activeTab.name() + "\t" + activeTab.url())
    case "url_title": return alfredArgs(activeTab.url() + "|" + activeTab.name())
    default: throw "Unrecognised type: " + outFormat
  }
}
